### ISSUE TITLE
Não remove os anexos

### ISSUE THREAD

**Issue by lagethomas** [smjesus/wordpress-plugin-remover-anexos#2]
Sérgio, tudo bem?
Testei o plugin em meu site, utilizo apenas campo media e ele não remove a midia após eu deletar o post.O Post é deletado de forma correta, mas a midia continua na galeria.
Eu não uso o Profile Builder nesse Projeto, pode ser por isso? É obrigatório o uso do Profile Builder?

**Comment by lagethomas** [comment]
> rio

na verdade acabei de descobrir. Eu uso os campos como Media URL e só aceita Media ID.
Como URL existirá a função para usar?
Quando usa o media id e tento testagar no front emn botão de edição por exemplo, não temho a URL do item e apenas o Id, isso faz com que o item não seja encontrado e não abra. É trabalhoso lidar com média id, média URL ele já me retorna a URL exata do arquivo com seu nome original e isso seria o ideal.

**Comment by smjesus** [comment]
> Sérgio, tudo bem? Testei o plugin em meu site, utilizo apenas campo media e ele não remove a midia após eu deletar o post.O Post é deletado de forma correta, mas a midia continua na galeria. Eu não uso o Profile Builder nesse Projeto, pode ser por isso? É obrigatório o uso do Profile Builder?

Olá Thomas!!! Desculpe a demora desta resposta!!

Não é obrigatório o uso do Profile Builder!!  Forte Abraço!!

**Comment by smjesus** [comment]
> > rio
> 
> na verdade acabei de descobrir. Eu uso os campos como Media URL e só aceita Media ID. Como URL existirá a função para usar? Quando usa o media id e tento testagar no front emn botão de edição por exemplo, não temho a URL do item e apenas o Id, isso faz com que o item não seja encontrado e não abra. É trabalhoso lidar com média id, média URL ele já me retorna a URL exata do arquivo com seu nome original e isso seria o ideal.

O uso do ID é mais prático, somente isto! Mas vc pode obter a URL a partir do ID, formatando a saída do campo com os 'callbacks'.

**Comment by lagethomas** [comment]
Consegui criar uma função que remove pela mida URL os itens relacionados.

Obrigado pelo Feedback.
